### ISSUE TITLE
Database names for MongoView should be configurable

### ISSUE THREAD

**Issue by srsp** [holunda-io/camunda-bpm-taskpool#152]
Currently we need to separate Mongo databases for axon data and task payload data when using the MongoView. It should be possible to use just one and the database names should be configurable.

**Comment by zambrovski** [comment]
Ok. There is a little misconception here. In fact, there should not be two Mongo databases for one projection. The idea is that the projection is responsible for the storage of the data it represents. Essentially, there are two way to achieve this. Either the projection is transient and relies on the replay on ever restart - it has transient storage of the elements (e.g. in memory) and transient storage of the global index reflecting the position in the event stream or it has a persistent storage for the elements and a persistent storage of the global index in the SAME storage. 

In the case of the Mongo projection we rely on the storage of the data and task elements in the collection "data-entry" and "tasks". The global index is stored by Axon in a collection "tracking-tokens". The remaining collections ("domain-events", "sagas", "snapshots") are configured but never used on the projection side (they are for the aggregate side). 

We should configure both sides (projection and axon) to use the SAME database in order to stay consistent in case of errors.

So I'll close this issue and create the new one to fix the problem
